# Generated by Django 2.2.6 on 2019-10-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_coordinate_trench'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trench',
            name='coordinate',
        ),
        migrations.AddField(
            model_name='trench',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='trench',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.DeleteModel(
            name='Coordinate',
        ),
    ]
