# Generated by Django 2.2.6 on 2019-10-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Find',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.IntegerField(default=0)),
                ('depository', models.CharField(max_length=250)),
                ('material', models.CharField(max_length=250)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('depth', models.FloatField(default=0)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
