# Generated by Django 2.2.6 on 2019-10-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_find'),
    ]

    operations = [
        migrations.AddField(
            model_name='find',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
