# Generated by Django 2.2.6 on 2019-10-29 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_finding'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrenchImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/trench')),
                ('trench', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Trench')),
            ],
        ),
    ]
