# Generated by Django 2.2.6 on 2019-10-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_trenchimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrenchImage',
        ),
    ]
