# Generated by Django 2.2.6 on 2019-10-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_trenchimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Area'),
            preserve_default=False,
        ),
    ]
