# Generated by Django 2.2.7 on 2019-11-22 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Trench',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('editor', models.CharField(max_length=250)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excavation.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Find',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.IntegerField(default=0)),
                ('depository', models.CharField(max_length=250)),
                ('material', models.CharField(max_length=250)),
                ('description', models.TextField(default='')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('depth', models.FloatField(default=0)),
                ('diameter', models.FloatField(default=0)),
                ('date', models.DateTimeField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excavation.Area')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excavation.Finding')),
                ('trench', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excavation.Trench')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('editor', models.CharField(max_length=250)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('depth', models.FloatField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excavation.Area')),
            ],
        ),
    ]
